name: Build
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          lfs: true

      - name: Typst
        uses: typst-community/setup-typst@v5
        with:
          typst-version: 0.14.2

      - name: List available fonts
        run: typst fonts --font-path fonts/ --variants

      - name: Debug fonts
        run: |
          git ls-files fonts/
          file fonts/* fonts/**/* 2>/dev/null | grep -v directory

      - name: Compile
        run: python3 .github/scripts/build.py

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: build pdf artifacts"
          file_pattern: "*/**/*.pdf"
